#!/usr/bin/env bash

## Web-based script to initialize Drude powered Drupal 8 site
## Usage:
##   dsh exec-url https://raw.githubusercontent.com/blinkreaction/drude-d8-testing/master/.drude/commands/web-init

# Abort if anything fails
set -e

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

# Yes/no confirmation dialog with an optional message
# @param $1 confirmation message
_confirm ()
{
	while true; do
		read -p "$1 [y/n]: " answer
		case ${answer} in
			[Yy]|[Yy][Ee][Ss] )
				break
				;;
			[Nn]|[Nn][Oo] )
				exit 1
				;;
			* )
				echo 'Please answer yes or no.'
		esac
	done
}

echo -e "${green}Drude powered Drupal 8 project setup${NC}"
echo "------------------------------------------------"
echo -e "Preparing to download Drupal 8 project to ${yellow}$(pwd)/drude-d8-testing${NC}"
_confirm "Continue with this folder?"
echo -e "${green_bg} INIT ${NC}${green} Cloning repository...${NC}"

git clone -b master https://github.com/blinkreaction/drude-d8-testing.git && \
	cd drude-d8-testing && \
	dsh init
